import React, { useMemo, useState } from "react";
import { useLocation } from "wouter";
import { BarChart3, Eye, LogIn, MessageCircle, PackageCheck, Plus, ShoppingBag, TrendingUp, Users } from "lucide-react";
import { CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";

const periodOptions = [7, 30, 90] as const;
const brl = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
const number = new Intl.NumberFormat("pt-BR");

function KpiCard({ label, value, detail, icon: Icon, tone = "red" }: { label: string; value: string; detail: string; icon: React.ElementType; tone?: "red" | "amber" | "violet" | "emerald" }) {
  const tones = { red: "bg-red-500/12 text-red-300", amber: "bg-amber-400/12 text-amber-200", violet: "bg-violet-400/12 text-violet-200", emerald: "bg-emerald-400/12 text-emerald-200" };
  return <article className="min-w-0 rounded-2xl border border-white/10 bg-white/[.045] p-4 sm:p-5"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-xs font-bold uppercase tracking-[.15em] text-white/40">{label}</p><p className="mt-3 truncate text-2xl font-black tracking-[-.04em] sm:text-3xl">{value}</p></div><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl ${tones[tone]}`}><Icon size={19}/></span></div><p className="mt-3 text-xs leading-5 text-white/45">{detail}</p></article>;
}

function AdminInsights() {
  const { user, loading, isAuthenticated } = useAuth();
  const [, navigate] = useLocation();
  const [days, setDays] = useState<number>(30);
  const [productId, setProductId] = useState("");
  const [amount, setAmount] = useState("");
  const [country, setCountry] = useState("");
  const [note, setNote] = useState("");
  const [soldAt, setSoldAt] = useState(() => new Date().toISOString().slice(0, 16));
  const utils = trpc.useUtils();
  const summaryQuery = trpc.analytics.summary.useQuery({ days }, { enabled: !!user && user.role === "admin" });
  const productsQuery = trpc.products.list.useQuery({ includeUnavailable: true }, { enabled: !!user && user.role === "admin" });
  const createSale = trpc.analytics.createSale.useMutation({
    onSuccess: () => { toast.success("Venda confirmada registrada no painel executivo."); setProductId(""); setAmount(""); setCountry(""); setNote(""); utils.analytics.summary.invalidate(); },
    onError: error => toast.error(error.message),
  });
  const summary = summaryQuery.data;
  const kpis = summary?.kpis;
  const funnel = useMemo(() => [
    { label: "Visitas de página", value: kpis?.pageViews || 0, tone: "bg-white/55" },
    { label: "Produtos vistos", value: kpis?.productViews || 0, tone: "bg-red-400" },
    { label: "Adições ao carrinho", value: kpis?.cartAdds || 0, tone: "bg-amber-300" },
    { label: "Conversas WhatsApp", value: kpis?.whatsappContacts || 0, tone: "bg-emerald-400" },
    { label: "Vendas confirmadas", value: kpis?.confirmedSales || 0, tone: "bg-violet-300" },
  ], [kpis]);
  const funnelMax = Math.max(...funnel.map(step => step.value), 1);

  if (loading) return <div className="grid min-h-screen place-items-center bg-[#0b0b0c] text-white/50">Carregando painel executivo...</div>;
  if (!isAuthenticated) return <div className="grid min-h-screen place-items-center bg-[#0b0b0c] px-6 text-center text-white"><div><div className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-red-600"><LogIn /></div><h1 className="mt-6 text-3xl font-black">Painel executivo Tone</h1><p className="mt-3 text-white/50">Entre com a conta proprietária para visualizar indicadores da loja.</p><Button onClick={() => startLogin()} className="mt-7 bg-red-600">Entrar como administrador</Button></div></div>;
  if (user?.role !== "admin") return <div className="grid min-h-screen place-items-center bg-[#0b0b0c] px-6 text-center text-white"><div><h1 className="text-3xl font-black">Acesso restrito</h1><p className="mt-3 text-white/50">Sua conta não possui permissão para visualizar estes dados.</p><Button onClick={() => navigate("/")} className="mt-7 bg-white text-black">Voltar à loja</Button></div></div>;

  const submitSale = (event: React.FormEvent) => {
    event.preventDefault();
    const normalizedAmount = amount.trim() ? Math.round(Number(amount.replace(".", "").replace(",", ".")) * 100) : null;
    if (amount.trim() && (normalizedAmount === null || !Number.isFinite(normalizedAmount) || normalizedAmount < 0)) return toast.error("Informe um valor de venda válido.");
    createSale.mutate({ productId: productId ? Number(productId) : null, saleType: productId ? "catalog" : "custom", amountCents: normalizedAmount, currency: "BRL", customerCountry: country.trim() || null, note: note.trim() || null, soldAt: new Date(soldAt).toISOString() });
  };

  return <div className="min-h-screen bg-[#0b0b0c] text-white">
    <header className="border-b border-white/10"><div className="container flex min-h-20 flex-wrap items-center justify-between gap-3 py-3 sm:flex-nowrap"><a href="/" className="flex shrink-0 items-center gap-3"><img src="/manus-storage/tone-market-logo_77240e37.jpg" alt="Tone Market" className="h-9 w-12 rounded-lg object-cover sm:h-10 sm:w-14"/><span className="text-[10px] uppercase tracking-widest text-white/35 sm:text-xs">Executive</span></a><div className="ml-auto flex items-center gap-2"><Button variant="outline" onClick={() => navigate("/admin")} className="h-9 border-white/10 px-3 text-xs text-white hover:bg-white/10 sm:h-10 sm:px-4 sm:text-sm">Catálogo</Button><Button variant="outline" onClick={() => navigate("/admin/videos")} className="h-9 border-white/10 px-3 text-xs text-white hover:bg-white/10 sm:h-10 sm:px-4 sm:text-sm">Vídeos</Button><Button variant="outline" onClick={() => navigate("/")} className="h-9 border-white/10 px-3 text-xs text-white hover:bg-white/10 sm:h-10 sm:px-4 sm:text-sm">Ver loja</Button></div></div></header>
    <main className="container py-7 sm:py-10"><div className="flex flex-col justify-between gap-5 xl:flex-row xl:items-end"><div><p className="text-xs font-bold uppercase tracking-[.25em] text-red-400">Visão executiva</p><h1 className="mt-3 text-3xl font-black tracking-[-.04em] sm:text-4xl">Decisões guiadas por interesse real.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-white/50 sm:text-base">Acompanhe o caminho entre a visita, o interesse pelo instrumento, o carrinho, a conversa no WhatsApp e a venda que foi confirmada pela Tone. Os dados começam a ser contabilizados a partir desta publicação.</p></div><div className="flex w-full gap-2 overflow-x-auto pb-1 xl:w-auto">{periodOptions.map(option => <button key={option} onClick={() => setDays(option)} className={`shrink-0 rounded-full px-4 py-2 text-sm font-bold transition ${days === option ? "bg-red-600 text-white" : "border border-white/10 text-white/55 hover:text-white"}`}>{option} dias</button>)}</div></div>
      <div className="mt-8 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><KpiCard label="Visitantes únicos*" value={number.format(kpis?.uniqueVisitors || 0)} detail="Estimativa por navegador anônimo no período." icon={Users}/><KpiCard label="Conversas WhatsApp" value={number.format(kpis?.whatsappContacts || 0)} detail={`${kpis?.contactRate || 0}% das visualizações iniciaram contato.`} icon={MessageCircle} tone="emerald"/><KpiCard label="Vendas confirmadas" value={number.format(kpis?.confirmedSales || 0)} detail={`${kpis?.saleConversion || 0}% de conversão sobre conversas.`} icon={PackageCheck} tone="violet"/><KpiCard label="Faturamento confirmado" value={brl.format((kpis?.revenueCents || 0) / 100)} detail="Somente vendas registradas manualmente pela Tone." icon={TrendingUp} tone="amber"/></div>
      <section className="mt-6 grid gap-6 xl:grid-cols-[1.3fr_.7fr]"><div className="rounded-3xl border border-white/10 bg-white/[.04] p-5 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-bold">Tendência comercial</h2><p className="mt-1 text-sm text-white/45">Visitas, contatos e vendas confirmadas por dia.</p></div><span className="rounded-full bg-white/5 px-3 py-1 text-xs text-white/45">últimos {summary?.rangeDays || days} dias</span></div><div className="mt-6 h-72 sm:h-80">{summary?.daily?.some(item => item.views || item.contacts || item.sales) ? <ResponsiveContainer width="100%" height="100%"><LineChart data={summary.daily} margin={{ top: 8, right: 8, left: -18, bottom: 0 }}><CartesianGrid stroke="rgba(255,255,255,.08)" vertical={false}/><XAxis dataKey="date" tickFormatter={value => value.slice(5).split("-").reverse().join("/")} stroke="rgba(255,255,255,.35)" fontSize={11} tickLine={false}/><YAxis stroke="rgba(255,255,255,.35)" fontSize={11} tickLine={false} allowDecimals={false}/><Tooltip contentStyle={{ background: "#151517", border: "1px solid rgba(255,255,255,.12)", borderRadius: 14 }} labelStyle={{ color: "#fff" }}/><Legend wrapperStyle={{ fontSize: 12, color: "#d4d4d8" }}/><Line type="monotone" dataKey="views" name="Visitas" stroke="#a1a1aa" strokeWidth={2} dot={false}/><Line type="monotone" dataKey="contacts" name="WhatsApp" stroke="#34d399" strokeWidth={2.5} dot={false}/><Line type="monotone" dataKey="sales" name="Vendas" stroke="#c4b5fd" strokeWidth={2.5} dot={false}/></LineChart></ResponsiveContainer> : <div className="grid h-full place-items-center rounded-2xl border border-dashed border-white/15 text-center"><div><Eye className="mx-auto text-white/20" size={30}/><p className="mt-3 font-semibold text-white/70">Aguardando os primeiros sinais.</p><p className="mt-1 max-w-xs text-sm leading-6 text-white/40">O gráfico aparecerá conforme visitantes navegam, adicionam itens e conversam com a Tone.</p></div></div>}</div></div>
        <aside className="rounded-3xl border border-white/10 bg-white/[.04] p-5 sm:p-7"><h2 className="text-xl font-bold">Funil de interesse</h2><p className="mt-1 text-sm text-white/45">Onde a atenção evolui até a venda.</p><div className="mt-6 space-y-5">{funnel.map(step => <div key={step.label}><div className="flex items-center justify-between gap-3 text-sm"><span className="text-white/65">{step.label}</span><strong>{number.format(step.value)}</strong></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white/8"><div className={`h-full rounded-full ${step.tone}`} style={{ width: `${Math.max((step.value / funnelMax) * 100, step.value ? 3 : 0)}%` }}/></div></div>)}</div><div className="mt-7 rounded-2xl border border-amber-300/15 bg-amber-300/[.045] p-4 text-xs leading-5 text-amber-100/70">Leitura recomendada: priorize instrumentos com muitas visualizações ou carrinhos, mas poucas conversas. Isso costuma indicar oportunidade de melhorar fotos, preço, descrição ou CTA.</div></aside></section>
      <section className="mt-6 grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><div className="rounded-3xl border border-white/10 bg-white/[.04] p-5 sm:p-7"><div className="flex items-start justify-between gap-3"><div><h2 className="text-xl font-bold">Produtos com mais intenção</h2><p className="mt-1 text-sm text-white/45">Visualizações, carrinhos, contatos e vendas no período.</p></div><ShoppingBag className="text-red-300" size={20}/></div>{summary?.topProducts?.length ? <div className="mt-6 overflow-x-auto"><table className="w-full min-w-[580px] text-left text-sm"><thead className="border-b border-white/10 text-xs uppercase tracking-[.12em] text-white/35"><tr><th className="pb-3 font-bold">Produto</th><th className="pb-3 text-right font-bold">Vistas</th><th className="pb-3 text-right font-bold">Carrinho</th><th className="pb-3 text-right font-bold">Contato</th><th className="pb-3 text-right font-bold">Vendas</th></tr></thead><tbody>{summary.topProducts.map(item => <tr key={item.productId} className="border-b border-white/5 last:border-0"><td className="py-4"><p className="font-semibold">{item.name}</p><p className="mt-1 text-xs text-white/40">{item.category}</p></td><td className="py-4 text-right text-white/65">{item.views}</td><td className="py-4 text-right text-white/65">{item.cartAdds}</td><td className="py-4 text-right text-emerald-200">{item.contacts}</td><td className="py-4 text-right text-violet-200">{item.sales}</td></tr>)}</tbody></table></div> : <div className="mt-6 rounded-2xl border border-dashed border-white/15 p-8 text-center text-sm text-white/40">Ainda não há interesse registrado por produto. Os dados começam a aparecer após as primeiras visitas e interações.</div>}</div>
        <form onSubmit={submitSale} className="rounded-3xl border border-violet-300/20 bg-violet-400/[.045] p-5 sm:p-7"><div className="flex items-start gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-violet-300/15 text-violet-200"><Plus size={19}/></span><div><h2 className="text-xl font-bold">Confirmar venda</h2><p className="mt-1 text-sm leading-6 text-white/50">Registre somente negócios finalizados no WhatsApp ou na loja. Esse registro alimenta faturamento e conversão reais.</p></div></div><div className="mt-6 space-y-4"><div><Label>Produto do catálogo (opcional)</Label><select value={productId} onChange={event => setProductId(event.target.value)} className="mt-2 h-11 w-full rounded-md border border-white/10 bg-black/25 px-3 text-sm text-white"><option value="">Projeto Custom / venda sem produto vinculado</option>{(productsQuery.data || []).map(product => <option key={product.id} value={product.id}>{product.name}</option>)}</select></div><div className="grid gap-4 sm:grid-cols-2"><div><Label>Valor final em reais</Label><Input value={amount} onChange={event => setAmount(event.target.value)} inputMode="decimal" placeholder="Ex.: 12500,00" className="mt-2 border-white/10 bg-black/25 text-white placeholder:text-white/25"/></div><div><Label>Data da venda</Label><Input type="datetime-local" value={soldAt} onChange={event => setSoldAt(event.target.value)} className="mt-2 border-white/10 bg-black/25 text-white"/></div></div><div><Label>País do comprador (opcional)</Label><Input value={country} onChange={event => setCountry(event.target.value)} placeholder="Ex.: Brasil, Estados Unidos" className="mt-2 border-white/10 bg-black/25 text-white placeholder:text-white/25"/></div><div><Label>Observação interna (opcional)</Label><Textarea value={note} onChange={event => setNote(event.target.value)} placeholder="Ex.: negociação via WhatsApp, instrumento de referência..." className="mt-2 min-h-20 border-white/10 bg-black/25 text-white placeholder:text-white/25"/></div><Button disabled={createSale.isPending} type="submit" className="h-12 w-full rounded-xl bg-violet-400 font-bold text-[#1a1022] hover:bg-violet-300"><PackageCheck size={18}/>Registrar venda confirmada</Button></div></form></section>
      <section className="mt-6 rounded-3xl border border-white/10 bg-white/[.03] p-5 sm:p-7"><div className="flex items-center justify-between gap-4"><div><h2 className="text-xl font-bold">Últimas vendas confirmadas</h2><p className="mt-1 text-sm text-white/45">Registro administrativo; não representa conversas ou carrinhos ainda em negociação.</p></div><BarChart3 className="text-white/30" size={22}/></div>{summary?.recentSales?.length ? <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{summary.recentSales.map(sale => <article key={sale.id} className="rounded-2xl border border-white/10 bg-black/20 p-4"><p className="text-xs font-bold uppercase tracking-[.12em] text-violet-200">{sale.saleType === "custom" ? "Custom" : "Catálogo"}</p><p className="mt-3 text-lg font-black">{sale.amountCents !== null ? brl.format(sale.amountCents / 100) : "Valor não informado"}</p><p className="mt-2 text-xs text-white/45">{sale.customerCountry || "Destino não informado"} · {new Date(sale.soldAt).toLocaleDateString("pt-BR")}</p></article>)}</div> : <p className="mt-5 text-sm text-white/40">Nenhuma venda confirmada foi registrada neste período.</p>}</section>
      <p className="mt-6 text-xs leading-5 text-white/30">* Visitantes únicos são estimados por identificador anônimo do navegador. A Tone não armazena nome, telefone, e-mail ou localização dos visitantes nesta análise.</p>
    </main>
  </div>;
}

export default AdminInsights;
